---

- name: Delete route object associated to kong service object
  uri:
    url:    "{{ kong_admin_api_url|default('http://localhost:8001') }}/routes/{{ matched_route_id }}"
    method: DELETE
    status_code: "204,404"
  register: route_del
  when: matched_route_id != ''

#- debug: var=route_del
